### ISSUE TITLE
availability quarantine

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa#1002]
Currently quarantined messages are only visible to the admin and domain admin. This eventhough the users have a  "quarantine" button and interface. Is this intentional? Is there a possibility for regular users to view messages that have been quarantined by the system on their behalf? Perhaps I missed a setting somewhere?

**Comment by tonioo** [comment]
The quarantine is available for every user but visibility depends on the role. Simple users will just see the messages sent to them (primary address or aliases). By the way, this issue is related to the amavis extension so it should be opened in the associated repository (https://github.com/modoboa/modoboa-amavis). Thank you.

**Comment by JayBeRayBearGun** [comment]
oops, sorry you are right, didn't realise that.
