### ISSUE TITLE
Failed to retrieve mailbox location

### ISSUE THREAD

**Issue by ktsmokolyuk** [modoboa/modoboa#1090]
# Impacted versions

* Modoboa: 1.7.2
* installer used: Yes
* Webserver: Nginx

Hi There,

Could you please assist. Recently I have installed the new version of modoboa 1.7.2
But what's strange, I can't remove any mail accounts, that I created earlier

I see this message on top:

**Failed to retrieve mailbox location (sudo: no tty present and no askpass program specified )**

**Comment by ktsmokolyuk** [comment]
**Fixed**
There was no sudo file **/etc/sudoers.d/modoboa**:
```
# This file was automatically installed on 2017-03-30T04:11:27.326034
modoboa ALL=(vmail) NOPASSWD: /usr/bin/doveadm
```

**Comment by tlesh989** [comment]
Version: 1.8.1
Installer used: Yes
Webserver: NGiNX

Also needed to add to /etc/sudoers.d/modoboa:

`uwsgi ALL=(vmail) NOPASSWD: /usr/bin/doveadm`

**Comment by bijanpiri** [comment]
I had same problem with 1.10.5 version  because I had typed my domain name first letter with capital case.
So I guess this cause some problem such as enter username in login page(when you do not enter same cases)  or delete domain which seems to search with lowercase which had not found any entry .

My problem solved by adding the same domain name with all lower case letters(so you have same domain name with different letter cases) and then deleting the First letter capital domain name.
