### ISSUE TITLE
Config option to disable widgets

### ISSUE THREAD

**Issue by yannfill** [modoboa/modoboa#1093]
* Modoboa: 1.7.2
* installer used: No
* Webserver: Apache

How to completely disable widgets in admin view ? Not displaying any RSS feed and sponsor widget ?

**Comment by tonioo** [comment]
It is currently not possible to disable those widgets.

**Comment by kryskool** [comment]
You cannot disable RSS feed, but you can change the URL for the RSS feed

**Comment by yannfill** [comment]
Could it be possible to show these widgets only to superadmin and not admins ?

Because I give admin rights to my customers so they can manage their domains, but it's me who choose to use Modoboa for this purpose, not them, so I think it's irrelevant to ask them to sponsor this project.

**Comment by tonioo** [comment]
This widget is not intended to ask people to sponsor Modoboa, it is just a way to let them know it is possible and give them an overview on how donations could be used. Modoboa is a free software that helps many people and needs help in return to stay sustainable. That's why a bit of communication is needed...
Anyway, I'll add a switch to disable this widget for domain admins.

**Comment by yannfill** [comment]
I am well aware of free software stakes, I was just pointing out that it's not my customers concern who did not (have the freedom to) choose to use it.

Thanks for your support.
