### ISSUE TITLE
System Unavailble utilize 100% resources

### ISSUE THREAD

**Issue by mzummo** [modoboa/modoboa#1187]
It looks like the modoboa log parser spikes to suck up all system resources causing nginx and other services to stop responding killing the email server.

**Comment by mzummo** [comment]
||||||||||||||||||||||||||||3060/12045MB]
  Swp[||                                                                   44/2691MB]

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
17262 root       20   0 1055M  825M 15508 R 99.5  6.9  0:44.82 /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py logparser

**Comment by mzummo** [comment]
also handle_,mailbox operations seems to cause high CPU usgae as well

**Comment by tonioo** [comment]
@mzummo Can you check the size of your log file please?

**Comment by tonioo** [comment]
@mzummo Have you found something interesting?

**Comment by tonioo** [comment]
Due to its inactivity, I close this issue.

**Comment by ionescu77** [comment]
This happened to me today.

This issue was good, i checked amillog and it was huge 700MB :o

Huge considering I just installed modoboa 1-2 months ago but did not migrate my email yet, so no active use.

I was surprised this multiple entries did not get blocked, by the fail2ban postfix default filter.

Had to block this IP manually.

Any experience with this anyone?

Merci

![image](https://user-images.githubusercontent.com/8016748/80287141-67f13200-8738-11ea-859e-0857a54346d6.jpeg)

![image](https://user-images.githubusercontent.com/8016748/80287144-6de71300-8738-11ea-8f75-755361894255.jpeg)

**Comment by ionescu77** [comment]
## possible fix

https://forum.iredmail.org/topic13866-dovecot-sasl-authentication-component-denial-of-service-attack.html
