### ISSUE TITLE
Difference between domain alias and relay domain

### ISSUE THREAD

**Issue by hadifarnoud** [modoboa/modoboa#1311]
how domain aliases work? do I need to do anything else other than adding them as an alias to a domain? it does not work for me.

so, I tried relay domain. that doesn't work either. what is the difference between relay domain and domain alias?

**Comment by tonioo** [comment]
An alias domain applies to every mailbox of a domain. For example, if you have a domain test.com which contains your mailboxes, if you create a test.org alias, then every mailbox will automatically have @test.org alias. For example:
* hadi@test.com (the original address)
* hadi@test.org (thanks to the domain alias)

A relay domain is different because your modoboa server is not the final destination. It is generally useful when modoboa acts as a filtering gateway for another SMTP server. In this case, you define a relay domain and relay it to the destination server.

**Comment by tonioo** [comment]
@hadifarnoud Does it answer your question?

**Comment by hadifarnoud** [comment]
yes, thank you.

**Comment by openaspace** [comment]
But when adding a domain relay, the DKIM PFS DMARK etc.. are still valid from the main domain?
