### ISSUE TITLE
Distribution lists

### ISSUE THREAD

**Issue by albertusgeyser** [modoboa/modoboa#1327]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ? Yes
* Webserver: Nginx/Apache

Distribution lists (Enhancement):

General
Address
The address of the distribution list. Messages sent to this address will be forwarded to all recipients on the distribution list.
Mode

    Public - Anyone can send to the list
    Membership - Only members can send to the list
    Announcements - Only messages to the list from a specific address will be allowed.

Require SMTP Authentication
If this checkbox is selected, MailServer will require SMTP authentication for deliveries made to the list. If you select this option, only users with accounts on the server will be able to send email to the distribution list.
Members
Add
Click Add to add an address to the distribution list.
Delete
Click Delete to remove the selected address from the distribution list.

**Comment by tonioo** [comment]
@albertusgeyser Are you talking about mailing lists? (like mailman) Or something more simple?

**Comment by RobbieBott** [comment]
@tonioo Are mailing list/distribution lists supported?
For example, (I am looking to switch from 1 and 1 for my email to Modoboa), with 1 and 1 I have distribution lists so I can send an email to staff@domain.com and everyone that has an email account within my domain will receive that email, and only email accounts with the @domain.com can email to that list, which prevents outsiders from sending emails to my entire staff, but allows my staff to simply type one email address to email everyone instead of having to go through their contacts and selecting each one.
From what I gather that is what Mailman GNU does. Are their plans for Modoboa to incorporate this feature?

**Comment by tonioo** [comment]
@RobbieBott Yes, Mailman is what you're looking for. There is no special plan right now but that's something we could do. I might propose a sponsoring about it in the future...

**Comment by carbans** [comment]
I think it's a good idea to give facilities to integrate modoboa with mailman. I will be happy to sponsor this feature if you add it.

**Comment by Franky1** [comment]
I would also like to see support for the **Mailman** mailing list in Modoboa!

**Comment by baby-gnu** [comment]
I see 2 use cases:

- define a sub domain to route completely to mailman
- get list of mailman mailing-lists and route them to the mailman server.
