### ISSUE TITLE
(Enhancement) - In-browser updating

### ISSUE THREAD

**Issue by neovisamal** [modoboa/modoboa#1337]
The status page in the admin UI for seeing currently installed vs. available version of each component is great. What would be greater is a Column on each row where available > current that allows me to have the system upgrade that component. 

Even if you couldn’t do it per component, having that function for the over all Modoboa versions would be awesome. Please don’t hesistate to reach out and ask for any clarifications, or even letting me know how much a sponsorship for this might be. Thanks!

**Comment by chumstick** [comment]
Kind of feel like this request is a waste of that glorious ticket number, Haha.

**Comment by tonioo** [comment]
@chumstick This is something not so easy to implement for many reasons:
* It requires access to the filesystem in order to install new versions (won't work in a docker environment for example)
* New versions sometimes require a manual modification of the settings.py file
* In a multi-node architecture (think about load balancing for example), each node must be updated...
* Last but not least, it would require to restart/reload the WSGI server (apache, uwsgi, ...) in order to load new versions

This is indeed an interesting feature but pretty complicated to implement. Unless you have another idea?

**Comment by kryskool** [comment]
Maybe this question must be move to https://github.com/modoboa/modoboa-installer ?

**Comment by stefaweb** [comment]
> This is indeed an interesting feature but pretty complicated to implement. Unless you have another idea?

And what do you think to add upgrade feature to run.py?

`sudo ./run.py --upgrade`

**Comment by tonioo** [comment]
I guess this sponsoring will interest all of you: https://modoboa.org/en/projects/8/.

;-)
