### ISSUE TITLE
Install Webmail SoGO

### ISSUE THREAD

**Issue by raf-rodrigues** [modoboa/modoboa#1567]
# Impacted versions

* Modoboa: Lastes
* installer used: Yes 
* Webserver: Nginx
 
Would it be possible to install SOGO's Webmail in the Modoboa installation?

Would Modoboa have any special configuration?

**Comment by Toniob** [comment]
Hi,
You can understand that the modoboa installer can't install all the available webmails wanted by the users. SOGO already have easy installation instructions. I don't think that adding it to modoboa would be really helpful.
There is no special configuration with Modoboa because you'll configure imap and smtp access in SOGO, nothing related directly to modoboa like its url or so
