### ISSUE TITLE
got "Domain does not exist" when I try to create a new user

### ISSUE THREAD

**Issue by IPv777** [modoboa/modoboa#1570]
# Impacted versions

* Modoboa: 1.10.6
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
use the installer on a fresh setup of Debian 9

# Current behavior
I can't create a new account, despite the domain name exists and the e-mail admin@mydomain.fr is working
![image](https://user-images.githubusercontent.com/19636346/45960897-8ef7f700-c01d-11e8-88b9-2823f6f4aa4a.png)

**Comment by tonioo** [comment]
@IPv777 What kind of user do you use?

**Comment by IPv777** [comment]
All types of users.
I got an error 400 from the server :/

-------- Message d'origine --------

**Comment by IPv777** [comment]
I'm trying to create an user with the super-admin account

-------- Message d'origine --------

**Comment by tonioo** [comment]
@IPv777 It is actually an issue related to case sensitivity. You defined a domain name containing upper case letters but Modoboa forces lower case email addresses when it validates the creation so the domain is not found (because IPv7.fr is different from ipv7.fr). The fix will require a bit of thinking because RFCs say domain names are case insensitive but local part (left side of the @) are. Modoboa is currently not consistent is the way it deal with case in domain names and addresses and I'm not sure what's the best rule to apply:

1.  Force lower case everywhere
2.  Force lower case only for local parts
3.  Do not lower case anything and fix authentication

What you can do if you're in a hurry is rename your domain to ipv7.fr and it will work.

@kryskool @fyfe Do you have any point of view about this?

**Comment by IPv777** [comment]
@tonioo yes, you was right :)
I just reinstalled modoboa with lower letters everywhere and now it's fully working ;)
Thanks for your time :) I sponsored a little part of the new feature ;)
