### ISSUE TITLE
Catch all mail

### ISSUE THREAD

**Issue by RT4U** [modoboa/modoboa#1580]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

Hi, how to create a catch all mail like, I wanted to send a mail with from address bounces(some random chars)@domain.com from the account admin@domain.com.

How to make one? Or is it even possible?

**Comment by jodumont** [comment]
Hi @RT4U 
related to different issues ([466](https://github.com/modoboa/modoboa/issues/466), [298](https://github.com/modoboa/modoboa/issues/298)) your not the first at looking for a catchall.

So this is the way I did it
hopefully; a contributor will tell us if mess with this config or everything is fine.
my answer is inspired from this [post](https://serverfault.com/questions/560906/postfix-virtual-aliases-and-catchall-for-undefined-addresses)

### 1. create `/etc/postfix/virtual` and add these lines
```
catchall@domain1.tld catchall@domain1.tld
@domain1.tld catchall@domain1.tld
@domain2.tld catchall@domain1.tld
@domain3.tld catchall@domain1.tld
```

NOTE: the 1st line, _where you redirect catchall on catchall_ is apparently very important
where domain1.tld is your main domain

### 2. reference /etc/postfix/virtual in /etc/postfix/main.cf
around the line 75
```
...
## Virtual transport settings
#
virtual_transport = lmtp:unix:private/dovecot-lmtp

virtual_mailbox_domains = proxy:pgsql:/etc/postfix/sql-domains.cf
virtual_alias_domains = proxy:pgsql:/etc/postfix/sql-domain-aliases.cf
virtual_alias_maps =
        proxy:pgsql:/etc/postfix/sql-aliases.cf
        hash:/etc/postfix/virtual
...
```
NOTE: _I gave you a context but I really just add the last line : `hash:/etc/postfix/virtual`_

### 3. create the database
`postmap /etc/postfix/virtual`
this command will generate the /etc/postfix/virtual.db

### 4. restart or reload postfix
`systemctl restart postfix`
`service postfix reload`

### 5. attribute catchall to a user
![untitled](https://user-images.githubusercontent.com/5204724/46906483-8a2fb000-cf04-11e8-803f-b309037a9521.jpg)

**Comment by RT4U** [comment]
Hi @jodumont 

Does this work for sending address?

Like I need to send with sender address as bounces-<randomcharacters>@domain.tld from admin@domain.tld.

**Comment by jodumont** [comment]
If I understand right your question and the project
I believe the account you create is for authentication
than the alias is for receiving email
and finally, **sender addresses** is where you add email you would like to use to send email but they are not an account and/or an alias
![untitled](https://user-images.githubusercontent.com/5204724/46915291-b3564c00-cfa9-11e8-93e8-f47fb48c389c.jpg)



such as 
you could have an _account_ : compta@domain.tld
and as an _alias_ the jean.bond@domain.tld because (Jean is your actual accountant)
and as _sender addresses_ you will add bill@domain.tld
to let's Jean sender bill through this address.

**Comment by RT4U** [comment]
I get it @jodumont

But that's not what I wanted. I need to the sender address to be a catch all address. Like jean@domain.tld could be able to send from bill<somerandomchars>@domain.tld instead of just bill@domain.tld

I've used it by editing postfix in the past, when I am setting up my own custom mail server, but I couldn't remember that. Is it possible to do it here?

**Comment by RT4U** [comment]
Oh lol, github removes the angle brackets, I just noticed it. I should be able to send with bill(some random chars)@domain.tld from jean@domain.tld. A catch all sender address.

@jodumont

**Comment by jodumont** [comment]
hum; I never ear about this
a quick look (because I'm curious :) let's me [found this](https://superuser.com/questions/1199492/how-to-setup-a-dynamic-sender-address-for-a-catchall-mail-address-with-dovecot-a) 

but you should definitely change the name of your issue for something like :
`how to setup a catch all sender address` or `how to setup a dynamic sender address`

**Comment by RT4U** [comment]
I don't know how to edit the title, but I've changed the description. Never thought GitHub would just cut whatever inside the angle brackets instead of normalising

**Comment by jodumont** [comment]
on stack overflow family site it's also hard to edit properly 
that's why I love screenshot :P


to edit your title you should have an **edit button**
![untitled](https://user-images.githubusercontent.com/5204724/46917004-75195680-cfc2-11e8-8ba0-e80912e8aef9.jpg)

**Comment by tonioo** [comment]
@RT4U Have you tried to add a sender address of the form @domain.tld to your account?

**Comment by RT4U** [comment]
I tried adding it. But didn't work. It stays that sender is not owned by admin@domain.tld

**Comment by tonioo** [comment]
@RT4U Can you provided a screenshot?
