### ISSUE TITLE
modoboa database collation?

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1619]
Hello!

Just one basic question.

For the modoboa database (with MariaDB), what is the best collation to use ?

utf8_general_ci
or
utf8mb4_unicode_ci
or
utf8mb4_general_ci

Sincerely,

**Comment by tonioo** [comment]
@stefaweb I'm not a MariaDB user so I can't really help you, sorry.

**Comment by Arvedui** [comment]
You should probably use `utf8mb4_unicode_ci`, assuming that you use a somewhat recent version. 

`utf8_general_ci` is not utf8 because mysql. It only allows for 3 Byte characters not 4 Byte.
`utf8mb4_general_ci` "just" sorts differently than the Unicode variant, which may or may not lead to unexpected results.

**Comment by tonioo** [comment]
@Arvedui Thank you for the answer :+1:
