### ISSUE TITLE
Can't connect with mail client thunderbird

### ISSUE THREAD

**Issue by minaeid90** [modoboa/modoboa#1671]
I can't connect to mail client like Thunderbird or on my android mail. I got a connection time out. The mail works fine on the web.

**Comment by tonioo** [comment]
@minaeid90 Looks like a firewall issue...

**Comment by fpiccinali** [comment]
@minaeid90 

Do you still have the issue ? 

If it is ok, can you close this issue ?

**Comment by Siriuo** [comment]
Seems to be an issue with SMTP authentication.

IMAP authentication seems to validate on android devices (Specifically using Boxer Mail) however SMTP doesn't appear to authenticate.

**Comment by Siriuo** [comment]
Okay found a solution to the issue. Turns out I was able to connect with one of my domains.

I had to duplicate the autoconfig.domain.com nginx config for the other domains. Following that I had to duplicate the mail.domain.com nginx config for the other domains. 

I then had to add the other domains to the ALLOWED_HOSTS section of /srv/modoboa/instance/instance/settings.py

This essentially resolves a few issues. Firstly the autoconfig/autodiscover for third party clients (android mail, thunderbird etc) and the webmail access for other domains.
