### ISSUE TITLE
DKIM and DMARC not valid

### ISSUE THREAD

**Issue by waiylgeek** [modoboa/modoboa#1757]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Added TXT record in DNS zone for DKIM and  DMARC as required and explained

# Current behavior
auth-results@verifier.port25.com returns:

```
SPF check:          none
"iprev" check:      pass
DKIM check:         permerror
SpamAssassin check: ham
```

# Video/Screenshot link
TXT records

![WhatsApp Image 2019-07-13 at 6 34 44 PM](https://user-images.githubusercontent.com/4692358/61174784-f70fcd80-a59c-11e9-84a9-32b03ff25908.jpeg)

Modoboa DNS check results
<img width="572" alt="Screen Shot 2019-07-13 at 6 33 15 PM" src="https://user-images.githubusercontent.com/4692358/61174771-b7e17c80-a59c-11e9-8225-bd60b6a7ac54.png">

**Comment by ihmc3jn09hk** [comment]
Check the server IP is in any blacklist. 

Some more info, even though I got all green-lights. Yahoo Mail! still put my mails into Bulk folder. Sad!

**Comment by tonioo** [comment]
Is it still happening?

**Comment by tsabi** [comment]
Hi!
What is exactly the FQDN of the key?

**Comment by DaveDischord** [comment]
I use GoDaddy as well and get a fail in both as well.  I'm using the names **modoboa._domainkey** and **_dmarc** without <example.com>.  mxtoolbox checks ok when, for example, I search with **modoboa._domainkey.example.com** and the value NOT in quotes.  I guess my question is, does modoboa tack on example.com in those checks and does it expect the value to be in quotations.

**Comment by tonioo** [comment]
@DaveDischord So, is there something to fix inside modoboa?

**Comment by DaveDischord** [comment]
> @DaveDischord So, is there something to fix inside modoboa?

No, it's the syntax on GoDaddy.  Under **Host** would be **modoboa._domainkey** or **_dmarc** WITHOUT .domain.tdl.  Under **TXT Value** would be whatever the value is encapsulated in quotation marks (**"**), for example **"v=DKIM1;k=........."**

**Comment by damko** [comment]
sorry for the necro posting but I think I can help anyone who's stumbling on this page:

Test DKIM key from you mailserver terminal:

    dig @dns_of_your_registar TXT your_dkim_key._domainkey.example.com

If the command exits saying "server not reachable" try this:

    dig @dns_of_your_registar TXT your_dkim_key._domainkey.example.com
    
`+vc` forces requests over TPC instead of UDP.

If the last command works but the first doesn't it means that your firewall is filtering UDP traffic.

When you get the `dig` command to work you can compare the result with the one displayed by Modoboa. They should not differ.

I've noticed that sometimes, depending on the generated value, the bottom box displayed by Modoboa contains some spaces " ". I advice to copy the value from the "Raw format" box and then to paste in a text edit to add the "v=" and "k=" parameters
