### ISSUE TITLE
DNSBL - Dynip.rothen.com Issue

### ISSUE THREAD

**Issue by isaaclepes** [modoboa/modoboa#2034]
dynip.rothen.com is returning a 503 service unavailable error.  Modoboa seems to interpret this as the server being listed.

**Comment by MrGeneration** [comment]
I'm using these:
```
postscreen_dnsbl_sites =
        zen.spamhaus.org*3
        bl.spameatingmonkey.net*2
        dnsbl.habl.org
        dnsbl.sorbs.net
```

I did remove one or two lists due to EOL or wrong results.
In my opinion that's more a postfix thing (interpreting wise). 

I also had a quick lurk into the code where the DNSBLs are defined:
https://github.com/modoboa/modoboa-installer/blob/c39adcbd143f1d07551a1f49089624917b7cb592/modoboa_installer/scripts/files/postfix/main.cf.tpl#L144-L148

I can't find above mentioned list and thus it seems you manually added it at some point?

**Comment by isaaclepes** [comment]
I didnt add any manually, or I would have removed it.  However, I did forget to check for updates and it appears to be resolved after updating all packages via apt.  Gussing this host was on an old version or something.
