### ISSUE TITLE
Active Directory Identity creation/Web login issues

### ISSUE THREAD

**Issue by DaveDischord** [modoboa/modoboa#2239]
Even by looking at the log files, I'm still stumped on where my problem is.  
First, my setup involves modoboa and dovecot syncing with Active Directory.  Dovecot syncing is not through Modoboa's parameter settings.  Most users that have mailboxes set up can access their mail.  Now, however, newly created AD users aren't able to log in Modoboa's web interface. 
 I've ran into the same error logging into Modboa's webmail using 2 different test users:
`**Error: Failed to update password: {'msgtype': 103, 'msgid': 3, 'result': 50, 'desc': 'Insufficient access', 'ctrls': [], 'info': '00000005: SecErr: DSID-031A1256, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n'}**`
- One user has an identity/mailbox in Modoboa.  User can create IMAP account under Outlook and Send.Receive emails through that app.
- A freshly created AD user gets the error logging into Modoboa.  No identity or User/Maildir folder is created at this point.  Attempting to create Outlook account, user can log into Incoming email server, but cannot send a test email, leading to a 553 error (Sender address rejected: not owned by user).  At this point, no Identity is created under Modoboa's web interface, but a User/Maildir is created alongside all others.

**Comment by DaveDischord** [comment]
Thanks.  I did update my cron file, but still having the same issue with all test users.  I've ran it manually with the following errors:
**As sudo**
`  File "/srv/modoboa/instance/manage.py", line 16
    ) from exc
         ^
SyntaxError: invalid syntax
`
**In virtual**
After adjusting the search filter under Parameters, it ran without error. 
The Identities section was then populated with other users based on filter, including test users; however, the error message still persists.  

- I've ran an Export on Identities and cells under the column containing the crypted passwords are blank for the test users or any user that has never accessed or hasn't been able to access webmail.

- I've changed all **manage.py** in the cron file except the vmail one to run as modoboa.  All commands executed without error except **manage.py update_statistics** which returned
`rrdtool.OperationalError: opening '/srv/modoboa/rrdfiles/new_accounts.rrd': Permission denied`

- After changes, I've restarted all relevant services and/or restarted the machine completely.

**Comment by tonioo** [comment]
@DaveDischord Your last error seems to be related to an ACL / permission issue on your LDAP server...

**Comment by im-fabian** [comment]
Am I missing something? Because for me it states that the command _import_from_ldap_directory_ does not exist.

```
(env) modoboa@mail:~/instance$ python manage.py import_from_ldap_directory
Unknown command: 'import_from_ldap_directory'
Type 'manage.py help' for usage.
```

**Comment by ScionOfDesign** [comment]
I am also running into this issue, which sucks because out of all the FOSS self-hosted email solutions with an admin panel I've tried, this is the _only_ one that seems to be able to be containerized (albeit with some difficulty) as well as has LDAP support as a flagship feature. Mailcow's 3rd-party LDAP plugin doesn't work, Docker-Mailserver requires a specific schema to work, and Mailu has no LDAP support. I would really like some help getting this to work.

Here's my setup:
For my LDAP provider am using a clean installation of FreeIPA.
I am using the docker image found [here ](https://hub.docker.com/r/ntninja/modoboa), located at [this ](https://gitlab.com/ntninja/docker-recipies/-/tree/master/modoboa) repository. From that image, I also installed the webmail and LDAP apps.
Getting it set up seemed to work fine. With internal accounts, I am able to send and receive emails without issue. When it comes to LDAP accounts, however, is when things get tricky. This is what I have discovered so far:

Trying to login to an LDAP account *without* a local account results in a big INVALID_CREDENTIALS error: https://dpaste.com/8LDAHQHKE

If I manually make a new local account with the same username as the LDAP account, but with a random password, then I am able to login with my LDAP credentials (just username, unlike local accounts, which require the domain too) but I get this error when visiting webmail:
`Error: [b'[AUTHENTICATIONFAILED] Authentication failed.']`


If I change the local password to match the LDAP password, then initially get this error the first time I visit Webmail:
`Error: [b'[SERVERBUG] Internal error occurred. Refer to server log for more information. [2021-06-02 18:46:12] (0.009 + 0.000 + 0.008 secs).']`

However, it loads after refreshing a bit and seems to work normally.

If I run 'manage.py import_from_ldap_directory', then it creates a local account but I get the same error, presumable because there is no local password. Attempting to give this account password results in an 'internal error' message popping up when I hit the 'edit' button on the user in the Admin panel.

As a side note, I cannot log in via LDAP with the fully qualified email of the LDAP user. It MUST be their username and not their email. I have not tested how LDAP resolves users with multiple email domains, but I can't imagine it would work.

**Comment by ScionOfDesign** [comment]
I FOUND THE BUG!
https://github.com/modoboa/modoboa/blob/aa91a783d1d40aeda482ff7e4010c617c39af826/modoboa/core/models.py#L120

This should be `ldap_enable_import` and NOT `ldap_enable_sync`. The code is trying to update the LDAP password with a local password that does not exist!
