### ISSUE TITLE
Frequent false positive DNSBL issues

### ISSUE THREAD

**Issue by jgfoster** [modoboa/modoboa#2679]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 22.04.1
* Database Type: PostgreSQL / MySQL
* Database version: 12.12
* Modoboa: 2.0.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Let system run normally.

# Current behavior

Notifications several times a day that "Modoboa detected that domain xxx.yyy is listed by the following DNSBL providers:". The providers are sbl.spamhaus.org and zen.spamhaus.org. When I go to spamhaus.org and look up my domain (less than a minute later) it says that it has no issues. This problem started in the last week or so. Can you describe why Modoboa is sending these messages and how I can address the problem?

# Expected behavior

Accurate report of spamhaus.org.

**Comment by Spitfireap** [comment]
Hi, a workarround has been deployed since 2.0.3. Bear in mind that If you're receiving false positive it likely means that you're using open dns solver (like 1.1.1.1). It is advised to [run your own dns resolver locally ](https://www.linuxbabe.com/ubuntu/set-up-local-dns-resolver-ubuntu-20-04-bind9) :).

**Comment by jgfoster** [comment]
I've upgraded to 2.0.3 and set up my own DNS resolver as recommended and the problem seems to have been resolved. Thanks so much for the prompt reply!
