### ISSUE TITLE
dovecot need restart after LE certificate reissue

### ISSUE THREAD

**Issue by lolhunter121** [modoboa/modoboa#3195]
After LE certificate reissue all services, except dovecot is restarted and use new certificate.
Dovecot use old certificate till restart, so mail clients show error that certificate has expired.

**Comment by Aegis8** [comment]
I encountered a similar issue today. Dovecot needed a manual reload to pick up the new certificate. 

Affected version 2.2.0
OS: Ubuntu 22.04.3 LTS

I do not have logs for the certificate renewal date anymore.

**Comment by xinomilo** [comment]
we face this problem since 06/2023, but not only dovecot. postfix too. we've been using following cron to restart services since : 

XX X * * X /usr/sbin/postmap -F hash:/etc/postfix/sni_map
XX X * * X /bin/systemctl restart postfix.service
XX X * * X /bin/systemctl restart dovecot.service

note, simply restarting postfix, without re-mapping sni_map, doesn't work. 
(Debian 11.9, modoboa 2.2.4.)
