### ISSUE TITLE
Possible to use as a front end mail gateway and NOT a complete mail system?

### ISSUE THREAD

**Issue by ravensorb** [modoboa/modoboa#986]
I am considering switching from ASSP to modoboa and I was curious if it is possible to setup things up so that modoboa is configured as a mail gateway with all mail (and users) residing on another system (like xmail or hMailServer)?

I know that I can do this with postfix and setting up relay_domains, relay_receipients, and transport configuration files, The question is -- will modoboa continue to work with this confirmation (including support for quarantine)?

**Comment by tonioo** [comment]
Yes, it will continue to work and you can even declare relay domains from Modoboa.

**Comment by ravensorb** [comment]
Awesome!  Any advice on setting it up?  Do I need to "sync" users to the database?  How can I set SMTP auth up to use the internal mail server?  How can I define the "routing rules" for the virtual domains?

**Comment by tonioo** [comment]
You don't need to sync anything, I suggest you start by creating a relay domain from the web interface, you should be asked for a destination (IP of hostname). I think that's what you call "routing rule"?
About the authentication, you can replace the default socket based authentication by a TCP one (ex: http://wiki2.dovecot.org/HowTo/PostfixAndDovecotSASL)

**Comment by ravensorb** [comment]
Ok, I already have SASL up and working on my current gateway.  So if I configure SASL to use my existing internal SMTP servers I should be good?  If I do that, and change the configure to point to my internal IMAP servers, do I even need dovecot anymore?

**Comment by tonioo** [comment]
According to your use case, you don't need dovecot.

**Comment by ravensorb** [comment]
Would users still be able to manage their quarantine?  And would I need to give them individual accounts or will they be able to login using their SMTP credentials?

**Comment by tonioo** [comment]
If you want users to manage their quarantine then Modoboa must know them, ie. you each must have a local account in order to authenticate...
An SMTP authentication plugin might be a good idea in this case (like the LDAP one), what do you think?

**Comment by ravensorb** [comment]
An SMTP auth plugin would be a great idea :)

**Comment by dragon2611** [comment]
When creating the relay domain there is the option between "relay" and "smtp" but also a scan button (which seems to just load a blank page),  However no where does it say what the difference between the options is.

**Comment by tonioo** [comment]
The 'service' corresponds to what is available inside postfix master.cf file. 'smtp' and 'relay' are always available. The 'scan' button tells Modoboa to parse this file in order to find additional services. I think you can choose the relay option.

**Comment by dragon2611** [comment]
Ah OK,

Eventually the accounts will be local anyway, but for now there is an existing server handling the actual email so the plan is for those domains to have modoboa act as the front end SMTP server and do spam filtering/scanning then passing it back to that server.

Presumably when I'm ready to switch I just change the domain type, or is it better to delete it and then re-add it.

**Comment by tonioo** [comment]
Changing the domain should be fine.

**Comment by dragon2611** [comment]
It's set as relay at the moment but looking at the postfix logs I seem to just return 450 service tempoarilly unavailable

**Comment by tonioo** [comment]
Can you paste your logs somewhere?

**Comment by dragon2611** [comment]
emailed to you providing they don't get eaten by a spam filter

**Comment by tonioo** [comment]
Which address?

**Comment by dragon2611** [comment]
The one that was in your profile.

**Comment by dragon2611** [comment]
It looks like if postscreen does any greylisting it doesn't play nice with o365 https://talk.plesk.com/threads/greylist-high-delays-from-protecction-outlook-com-and-others.334180/

https://talk.plesk.com/threads/enabling-postscreen-breaks-usr-local-psa-admin-sbin-mchk-command.333516/#post-781803

**Comment by tonioo** [comment]
Indeed, I don't see anything strange in your log file. You can try to whitelist o365 IPs at postscreen level.

**Comment by dragon2611** [comment]
Where does the installer put the config file?

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by tonioo** [comment]
At the regular place: /etc/postfix/main.cf.

**Comment by almereyda** [comment]
For us it is also neccessary to use Modoboa as a front-end mail gateway in front of various listserv instances, i.e. mailman, sympa and alike.

Unfortunately it is not perfectly clear how to:

* set up a relay host which uses a non standard port
i.e. putting `lists.allmende.io:1025` for debug reasons creates a transport rule to `[lists.allmende.io:1025]` instead of `[lists.allmende.io]:1025`
* have incoming mail to the relay domain passed without checking for existing accounts
i.e. answering to a mailman confirm message returns `Recipient address rejected: unverified address: unknown mail transport error;` in the mail log.

This needs better overall documentation, as the official one is silent on these subjects.
In the future, also the sending route should work via `SASL` auth to Modoboa, transparently accepting all sender addresses after authentication for that domain.

- Sender alias for such an account would just need to be `@relay.domain`?
- Local mailboxes and aliases are preferred over relaying?

**Comment by tonioo** [comment]
@almereyda The rule is improperly generated because modoboa does not split host and port information for now, that's something pretty easy to fix. About recipient address verification, just uncheck the "Verify recipients" option and you're done.
About the other part of your, I'm not sure to understand it...

**Comment by tonioo** [comment]
@ravensorb The SMTP authentication backend is done and will be released with 1.7.0.
@almereyda I've fixed the relaydomain bug (wrong syntax when using a port).
I close this issue, do not hesitate to open new ones if needed.
